/**
 * This file was generated by code.store CLI.
 *
 * By default you should be placing your resolvers in _src/resolvers/queries_ or _src/resolvers/mutations_ directories.
 * Use this file in the case when it is not possible to handle your use-case with the above directories.
 *
 * Both Queries and Mutations are optional and can be added here.
 *
 * Example of the structure:
 * export default {
 *   Query: {
 *     exampleQuery(parent, args, context, info) {
 *       return 'Hello, World!';
 *     },
 *   },
 *   Mutation: {
 *     exampleMutation(parent, args, context, info) {
 *       return true;
 *     },
 *   },
 * };
 */

export default {
  Query: {},
  Mutation: {},
};
